USE edustand_db;
ALTER TABLE Users ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE Users ADD COLUMN created_by INT NULL;
ALTER TABLE Users ADD FOREIGN KEY (created_by) REFERENCES Users(user_id) ON DELETE SET NULL;

ALTER TABLE Notices ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE Notices ADD COLUMN last_edited_by INT NULL;
ALTER TABLE Notices ADD FOREIGN KEY (last_edited_by) REFERENCES Users(user_id) ON DELETE SET NULL;

ALTER TABLE ContactRequests ADD COLUMN updated_by INT NULL;
ALTER TABLE ContactRequests ADD FOREIGN KEY (updated_by) REFERENCES Users(user_id) ON DELETE SET NULL;
